### PR TITLE
Be more lenient in accepting command inputs

### LINKED ISSUE #398: TypeError: (s || "").replace is not a function
**Describe the bug**
When trying to run an action, I am getting the following error from `@actions/core`:

```
(node:2588) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/command.js:27:5)
    at error (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/core.js:127:15)
    at Object.setFailed (/home/runner/work/_actions/cutenode/action-meeting/dev/node_modules/@actions/core/lib/core.js:101:5)
    at action (/home/runner/work/_actions/cutenode/action-meeting/dev/index.js:62:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Last commit where it works:
- https://github.com/cutenode/action-meeting/commit/f88068b6ec7c79c60712f1ec7cedf71d13aaada4

It stops working in this commit:
- https://github.com/cutenode/action-meeting/commit/71fa544290caaf49e3d17626208b5b9c2a3875dc

**EDIT:** Updated to only reflect the commit it stopped working in. This was triggered by passing an incorrect type to Octokit.js for the `labels` property - I was passing a string and it required an array. Since the project was erroring because of that and the error being passed was not a string, I was encountering this issue.

**Expected behavior**
For `@actions/core` to handle errors more effectively.

### PR DESCRIPTION
**Pull request by thboop**
Users have been encountering friction when trying to use command inputs.

[This commit](https://github.com/actions/toolkit/commit/8b0300129f08728419263b016de8630f1d426d5f#diff-30c957fdb0e7818041c155a0e3ac6e0b) broke some our handling when users don't pass in strings. We re-added that handling and implemented a test for it. 

We also have had a number of users ask for additional input types. 
https://github.com/actions/toolkit/issues/386 -> Set Failed and Error should accept errors
https://github.com/actions/toolkit/issues/370 -> Set Output should format data into strings

This commit resolves those use cases.

Resolves #398, #386, #370

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
interested in @ericsciple feedback

File: packages/core/src/command.ts [hunk 1]
```diff
@@ -61,14 +61,16 @@ class Command {
             } else {
               cmdStr += ','
             }
-
-            cmdStr += `${key}=${escapeProperty(val)}`
+            // safely escape the property - avoid blowing up when attempting to
```
Comment (ericsciple) [inline packages/core/src/command.ts:64]: Should we fix the typings instead?

Comment (ericsciple) [inline packages/core/src/command.ts:64]: It looks like these lines should be reverted. The functions `escapeData` and `escapeProperty` already OR the value with empty string

File: packages/core/src/core.ts [hunk 2]
```diff
@@ -204,3 +214,20 @@ export function saveState(name: string, value: string): void {
 export function getState(name: string): string {
   return process.env[`STATE_${name}`] || ''
 }
+
+/**
+ * Sanatizes an input into a string so it can be passed into issueCommand safely
+ * @param input input to sanitize into a string
+ */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+function sanitizeInput(input: any): string {
```
Comment (ericsciple) [inline packages/core/src/core.ts:223]: Would `toCommandValue` (or something similar) be a better name? "Sanitize" seems like a misnomer.

File: packages/core/src/core.ts [hunk 3]
```diff
@@ -204,3 +214,20 @@ export function saveState(name: string, value: string): void {
...
+  if (input == null) {
+    return ''
+  } else if (typeof input === 'string' || input instanceof String) {
+    return input as string
+  } else if (input instanceof Error) {
+    return input.toString()
+  } else {
```
Comment (ericsciple) [inline packages/core/src/core.ts:230]: should special case `null` and `undefined` (return empty string)

File: packages/core/src/core.ts [hunk 4]
```diff
@@ -204,3 +214,20 @@ export function saveState(name: string, value: string): void {
...
   return process.env[`STATE_${name}`] || ''
 }
+
+/**
+ * Sanatizes an input into a string so it can be passed into issueCommand safely
+ * @param input input to sanitize into a string
+ */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+function sanitizeInput(input: any): string {
+  if (input == null) {
```
Comment (ericsciple) [inline packages/core/src/core.ts:224]: suprised linter didnt complain. Can we check `=== null` and `=== undefined`?

File: packages/core/src/core.ts [hunk 5]
```diff
@@ -191,8 +198,11 @@ export async function group<T>(name: string, fn: () => Promise<T>): Promise<T> {
  * @param     name     name of the state to store
  * @param     value    value to store
  */
-export function saveState(name: string, value: string): void {
-  issueCommand('save-state', {name}, value)
+export function saveState(
+  name: string,
+  value: string | number | boolean
```
Comment (ericsciple) [inline packages/core/src/core.ts:203]: if we accept any, shouldnt we fix the type to be any? and comment should describe behavior (e.g. tojson for objects)

File: packages/core/src/core.ts (hunk 2 above)
Comment (ericsciple) [inline packages/core/src/core.ts:223]: have you considered driving this change into command.ts instead? Lowest level would be `escapeData` and `escapeProperty` function to call.

File: packages/core/src/core.ts [hunk 6]
```diff
@@ -121,8 +128,8 @@ export function debug(message: string): void {
  * Adds an error issue
  * @param message error issue message
  */
-export function error(message: string): void {
-  issue('error', message)
+export function error(message: string | Error): void {
```
Comment (ericsciple) [inline packages/core/src/core.ts:131]: should `warning` allow Error also?

File: packages/core/src/core.ts [hunk 7]
```diff
@@ -204,3 +214,20 @@ export function saveState(name: string, value: string): void {
...
+ * Sanatizes an input into a string so it can be passed into issueCommand safely
+ * @param input input to sanitize into a string
+ */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+function sanitizeInput(input: any): string {
+  if (input == null) {
+    return ''
+  } else if (typeof input === 'string' || input instanceof String) {
+    return input as string
+  } else if (input instanceof Error) {
```
Comment (ericsciple) [inline packages/core/src/core.ts:228]: is converting error to string only something the error/setFailed functions should do? I'm thinking about the description for the setOutput function... seems like weird behavior.

File: packages/core/src/core.ts (hunk 4 above)
Comment (thboop) [reply packages/core/src/core.ts:224]: Thats intentional but we can make it more clear.

```
null == undefined
true
null == null
true
null === undefined
false
null === null
true
```

File: packages/core/src/command.ts (hunk 1 above)
Comment (thboop) [reply packages/core/src/command.ts:64]: Those functions only || with an empty string if the value passed is falsey. Booleans, ints, and objects with no `.replace` function crash when passed into those functions because `123 || ""` will return 123.

File: packages/core/src/core.ts (hunk 2 above)
Comment (thboop) [reply packages/core/src/core.ts:223]: Setting process.env in exportVariable makes that hard
https://github.com/actions/toolkit/pull/405/files#diff-396527b4d62db15ebbfb2845654a161fR43

Comment (ericsciple) [reply packages/core/src/core.ts:223]: Ah good point regarding process.env.

Is command.ts internal only? If so then it should assume type is always string. Otherwise should update types to allow any.

File: packages/core/src/core.ts (hunk 6 above)
Comment (thboop) [reply packages/core/src/core.ts:128]: I enabled this for warning. I don't think we need to enable it for info or debug at this time, but if we get feature requests for it we can.

File: packages/core/src/command.ts [hunk 8]
```diff
@@ -61,27 +64,42 @@ class Command {
             } else {
               cmdStr += ','
             }
-
+            // safely escape the property - avoid blowing up when attempting to
```
Comment (ericsciple) [inline packages/core/src/command.ts:67]: it looks like these comments can be deleted now: `safely escape [...]`

now the type is `any` so `for some reason` language not needed anymore

**Comment by jasonkarns** [comment]
Late to the party here ( 🎉 for resolving!!)... but shouldn't the `Error` stringification use `e.message` instead of `e.toString()`? The `toString` method prepends `"Error: "`, to the message which is likely redundant and not desirable.
